### ISSUE TITLE
`Vitals.time` is undefined

### ISSUE THREAD

**Issue by why-el** [jondot/vitals#14]
It is not delegated by the `Vitals` module to the underlaying reporter like the other methods. Any reason for this? Or just a bug?

**Comment by jondot** [comment]
Hi!, checking this now.

**Comment by jondot** [comment]
No special reason. I think this idea was brought up before as well so we'll add it to the next version. If you want to submit a PR to accelerate the process you are welcome.

**Comment by why-el** [comment]
Sure give me 10 minutes or so.

**Comment by jondot** [comment]
Actually, I already did it, pushing a PR now :)

**Comment by why-el** [comment]
Haha, cool, I was about to finish the spec as well. Thanks for the fast response.

**Comment by jondot** [comment]
👍  so now we'll just wait for the CI tests to go green. You can expect a new version in a little while.

**Comment by why-el** [comment]
Great, and for now accessing the reporter directly worked like a charm, so no rush.

**Comment by jondot** [comment]
Should be up on Rubygems now!
Feel free to close the issue once you've verified all is good for you 👍

**Comment by why-el** [comment]
Works great. :)
